with-expecter: true
packages:
  github.com/mholtzscher/weather-archiver/internal/dal:
    config:
      dir: "internal/testing/mocks"
      outPkg: "mocks"
    interfaces:
      # select the interfaces you want mocked
      Querier:
        config:
