services:
  db:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather-archiver
      TS_TUNE_MEMORY: 1GB
      TS_TUNE_NUM_CPUS: 4
      TS_TUNE_MAX_BG_WORKERS: 4
      TS_TUNE_MAX_CONNS: 20
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
