// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Sensor struct {
	ID        int32
	Source    string
	CreatedAt pgtype.Timestamptz
}

type SensorDatum struct {
	Time         pgtype.Timestamptz
	SensorID     int32
	NumericValue pgtype.Float8
	TextValue    pgtype.Text
	Data         []byte
}
