// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Driver struct {
	ID           int32
	FirstName    string
	LastName     string
	PlaceOfBirth string
	DateOfBirth  pgtype.Date
}

type Race struct {
	ID       int32
	SeasonID int32
	Name     string
	Location string
	Date     pgtype.Date
}

type Result struct {
	ID       int32
	RaceID   int32
	DriverID int32
	TeamID   int32
	Position int32
	Points   float64
}

type Season struct {
	ID         int32
	SeasonYear int32
	Series     string
}

type Team struct {
	ID   int32
	Name string
	Base string
}
