// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Sensor struct {
	ID       int32
	Type     pgtype.Text
	Location pgtype.Text
}
