// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dal

import (
	"context"
)

type Querier interface {
	GetSensors(ctx context.Context) ([]Sensor, error)
}

var _ Querier = (*Queries)(nil)
