// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sensors.sql

package dal

import (
	"context"
)

const getSensors = `-- name: GetSensors :many
select id, type, location from sensors
`

func (q *Queries) GetSensors(ctx context.Context) ([]Sensor, error) {
	rows, err := q.db.Query(ctx, getSensors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sensor
	for rows.Next() {
		var i Sensor
		if err := rows.Scan(&i.ID, &i.Type, &i.Location); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
