// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: team.sql

package dal

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO team 
(name, base)
VALUES (
$1, $2
)
RETURNING id
`

type CreateTeamParams struct {
	Name string
	Base string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Base)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getTeamById = `-- name: GetTeamById :one
SELECT id, name, base FROM team
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeamById(ctx context.Context, id int32) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamById, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.Base)
	return i, err
}
